# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: "Mohamed Fathi Abdallah"
author: "Mohamed Fathi Abdallah"
description: "Mohamed Fathi Abdallah Â©2023"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
icon: ðŸ§  # the emoji used as the favicon
mathjax: true
url: "http://www.mfathiabdallah.com" # the base hostname & protocol for your site

# Layout
show_social: true 
show_excerpts: false      # show article excerpts on the home page
show_frame: true          # adds a gray frame to the site
show_sidebar: false       # show a sidebar instead of the usual header
minimal: false            # use a dark header

# Menu

navigation:          # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV & Publications", file: "publications.md"}
  - {title: "More About Me", file: "more_about_me.md"}
  - {title: "News & Views", file: "blogs.md"}
  - {title: "Contact", file: "contact.md"}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:mohamed.fathi@ugent.be"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/MoFathiAbdallah"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/mohamed-fathi-abdallah-66126a38/"}
  - {title: Researchgate, icon: researchgate, url: "https://www.researchgate.net/profile/Mohamed-Abdallah-13"}
  - {title: GoogleScholar, icon: user-graduate, url: "https://scholar.google.com/citations?user=05FfukgAAAAJ&hl=en"}
  - {title: Orcid, icon: orcid, url: "https://orcid.org/0000-0002-3903-6452"}
  - {title: Ghent University, icon: landmark, url: "https://www.ugent.be/"}
  - {title: "Visitors", icon: "<img src='https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fwww.fathiabdallah.com&count_bg=%2379C83D&title_bg=%23555555&icon=&icon_color=%23E7E7E7&title=Visitors&edge_flat=false' alt='visitors count'>", url: "https://hits.seeyoufarm.com"} 
  - {title: Visitors, icon: fas fa-chart-line, url: "https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fwww.fathiabdallah.com&count_bg=%2379C83D&title_bg=%23555555&icon=&icon_color=%23E7E7E7&title=Visitors&edge_flat=false", target: "_blank", rel: "noopener"}

 #- {title: Github, icon: github, url: "https://github.com/mfathiabdallah"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/


plugins:
 - jekyll-feed
 - jemoji
 - jekyll-archives
 - jekyll-diagrams
 - jekyll-email-protect
 - jekyll-github-metadata
 - jekyll-imagemagick
 - jekyll-paginate-v2
 - jekyll/scholar
 - jekyll-sitemap
 - jekyll-target-blank
 - jekyll-twitter-plugin
 - jekyll-gist
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-toc
 - jekyll-redirect-from
 - jekyll-remote-theme
 

